# Generated by Django 5.1.6 on 2025-02-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_event_date_event_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('ds', 'Data Science'), ('cs', 'Computer Science')], default='ds', max_length=20),
        ),
    ]
