# Generated by Django 5.1.6 on 2025-02-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.CharField(choices=[('ds', 'Data Science'), ('cs', 'Computer Science')], default='ds', max_length=20),
        ),
    ]
