# Generated by Django 5.1.6 on 2025-02-26 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_event_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='department',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.ManyToManyField(blank=True, to='myapp.department'),
        ),
    ]
