# Generated by Django 5.1.6 on 2025-02-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('ds', 'Data Science'), ('cs', 'Computer Science')], max_length=20),
        ),
    ]
