# Generated by Django 5.1.6 on 2025-02-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_template',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_templates'),
        ),
    ]
