# Generated by Django 5.1.6 on 2025-02-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
